import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";

const bool = (v: FormDataEntryValue | null) => v === "on" || v === "true";
const str = (fd: FormData, key: string) => String(fd.get(key) || "");
const tags = (value: string) => value.split(",").map((x) => x.trim()).filter(Boolean);
const json = (value: string) => { try { return value ? JSON.parse(value) : undefined; } catch { return undefined; } };

export async function savePage(fd: FormData) { "use server"; await requireAdmin(); await db.page.upsert({ where: { slug: str(fd,"slug") }, create: { title: str(fd,"title"), slug: str(fd,"slug"), contentHtml: str(fd,"contentHtml"), seoTitle: str(fd,"seoTitle"), seoDescription: str(fd,"seoDescription"), seoImage: str(fd,"seoImage"), published: bool(fd.get("published")) }, update: { title: str(fd,"title"), contentHtml: str(fd,"contentHtml"), seoTitle: str(fd,"seoTitle"), seoDescription: str(fd,"seoDescription"), seoImage: str(fd,"seoImage"), published: bool(fd.get("published")) } }); revalidatePath("/"); redirect("/admin/pages"); }
export async function saveSection(fd: FormData) { "use server"; await requireAdmin(); const pageSlug = str(fd,"pageSlug") || "home"; const page = await db.page.upsert({ where: { slug: pageSlug }, create: { slug: pageSlug, title: pageSlug, contentHtml: "", published: true }, update: {} }); const id=str(fd,"id"); const data={ pageId: page.id, type: str(fd,"type"), title: str(fd,"title"), subtitle: str(fd,"subtitle"), contentHtml: str(fd,"contentHtml"), imageUrl: str(fd,"imageUrl"), videoUrl: str(fd,"videoUrl"), buttonText: str(fd,"buttonText"), buttonUrl: str(fd,"buttonUrl"), sortOrder: Number(str(fd,"sortOrder")||0), settingsJson: json(str(fd,"settingsJson")) }; if(id) await db.section.update({where:{id},data}); else await db.section.create({data}); revalidatePath("/"); redirect("/admin/sections"); }
export async function saveBlog(fd: FormData) { "use server"; await requireAdmin(); await db.blogPost.upsert({ where:{slug:str(fd,"slug")}, create:{ title:str(fd,"title"), slug:str(fd,"slug"), excerpt:str(fd,"excerpt"), contentHtml:str(fd,"contentHtml"), featuredImage:str(fd,"featuredImage"), category:str(fd,"category"), tags:tags(str(fd,"tags")), seoTitle:str(fd,"seoTitle"), seoDescription:str(fd,"seoDescription"), seoImage:str(fd,"seoImage"), published:bool(fd.get("published")) }, update:{ title:str(fd,"title"), excerpt:str(fd,"excerpt"), contentHtml:str(fd,"contentHtml"), featuredImage:str(fd,"featuredImage"), category:str(fd,"category"), tags:tags(str(fd,"tags")), seoTitle:str(fd,"seoTitle"), seoDescription:str(fd,"seoDescription"), seoImage:str(fd,"seoImage"), published:bool(fd.get("published")) }}); revalidatePath("/blog"); redirect("/admin/blog"); }
export async function saveProduct(fd: FormData) { "use server"; await requireAdmin(); await db.product.upsert({ where:{slug:str(fd,"slug")}, create:{ title:str(fd,"title"), slug:str(fd,"slug"), price:str(fd,"price")||"0", shortDescription:str(fd,"shortDescription"), longDescriptionHtml:str(fd,"longDescriptionHtml"), imageUrl:str(fd,"imageUrl"), galleryJson:json(str(fd,"galleryJson")), productType:str(fd,"productType")||"service", downloadFileUrl:str(fd,"downloadFileUrl"), seoTitle:str(fd,"seoTitle"), seoDescription:str(fd,"seoDescription"), seoImage:str(fd,"seoImage"), published:bool(fd.get("published")) }, update:{ title:str(fd,"title"), price:str(fd,"price")||"0", shortDescription:str(fd,"shortDescription"), longDescriptionHtml:str(fd,"longDescriptionHtml"), imageUrl:str(fd,"imageUrl"), galleryJson:json(str(fd,"galleryJson")), productType:str(fd,"productType")||"service", downloadFileUrl:str(fd,"downloadFileUrl"), seoTitle:str(fd,"seoTitle"), seoDescription:str(fd,"seoDescription"), seoImage:str(fd,"seoImage"), published:bool(fd.get("published")) }}); revalidatePath("/shop"); redirect("/admin/products"); }
export async function savePodcast(fd: FormData) { "use server"; await requireAdmin(); await db.podcastEpisode.upsert({ where:{slug:str(fd,"slug")}, create:{ title:str(fd,"title"), slug:str(fd,"slug"), youtubeUrl:str(fd,"youtubeUrl"), spotifyUrl:str(fd,"spotifyUrl"), appleUrl:str(fd,"appleUrl"), guestName:str(fd,"guestName"), descriptionHtml:str(fd,"descriptionHtml"), imageUrl:str(fd,"imageUrl"), published:bool(fd.get("published")) }, update:{ title:str(fd,"title"), youtubeUrl:str(fd,"youtubeUrl"), spotifyUrl:str(fd,"spotifyUrl"), appleUrl:str(fd,"appleUrl"), guestName:str(fd,"guestName"), descriptionHtml:str(fd,"descriptionHtml"), imageUrl:str(fd,"imageUrl"), published:bool(fd.get("published")) }}); revalidatePath("/podcast"); redirect("/admin/podcast"); }
export async function saveQuiz(fd: FormData) { "use server"; await requireAdmin(); const id=str(fd,"id"); const data={question:str(fd,"question"),type:str(fd,"type")||"text",optionsJson:json(str(fd,"optionsJson")),required:bool(fd.get("required")),sortOrder:Number(str(fd,"sortOrder")||0),active:bool(fd.get("active"))}; if(id) await db.quizQuestion.update({where:{id},data}); else await db.quizQuestion.create({data}); redirect("/admin/quiz"); }
export async function saveSettings(fd: FormData) { "use server"; await requireAdmin(); const first=await db.siteSetting.findFirst(); const data={siteName:str(fd,"siteName"),siteDescription:str(fd,"siteDescription"),logoUrl:str(fd,"logoUrl"),faviconUrl:str(fd,"faviconUrl"),googleAnalytics:str(fd,"googleAnalytics"),googleSearchConsole:str(fd,"googleSearchConsole"),facebook:str(fd,"facebook"),instagram:str(fd,"instagram"),youtube:str(fd,"youtube"),spotify:str(fd,"spotify"),tiktok:str(fd,"tiktok"),telegram:str(fd,"telegram"),whatsapp:str(fd,"whatsapp"),twitter:str(fd,"twitter"),linkedin:str(fd,"linkedin")}; if(first) await db.siteSetting.update({where:{id:first.id},data}); else await db.siteSetting.create({data}); revalidatePath("/"); redirect("/admin/settings"); }
export async function updateApplicationStatus(fd: FormData) { "use server"; await requireAdmin(); await db.interviewApplication.update({where:{id:str(fd,"id")},data:{status:str(fd,"status") as any}}); redirect("/admin/applications"); }
